global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'resource-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['resource-service:8081', 'song-service:8082', 'resource-processor:8083', 'storage-service:8084', 'resource-gateway:8080']
