spring:
  config:
    import: optional:configserver:http://localhost:8090
  cloud:
    gateway:
      routes:
        ## Resource Service
        - id: resource-service
          uri: http://localhost:8081
          predicates:
            - Path=/resource-service/**
          filters:
            - StripPrefix=1
        ## Song Service
        - id: song-service
          uri: http://localhost:8082
          predicates:
            - Path=/song-service/**
          filters:
            - StripPrefix=1
        ## Resource Processor
        - id: resource-processor
          uri: http://localhost:8083
          predicates:
            - Path=/resource-processor/**
          filters:
            - StripPrefix=1
        ## Storage Service
        - id: storage-service
          uri: http://localhost:8084
          predicates:
            - Path=/storage-service/**
          filters:
            - StripPrefix=1
        ## Grafana
        - id: resource-grafana
          uri: http://localhost:3000
          predicates:
            - Path=/grafana/**
          filters:
            - RewritePath=/grafana/(?<path>.*), /$\{path}
        ## Kibana
        - id: resource-kibana
          uri: http://localhost:5601
          predicates:
            - Path=/kibana/**
          filters:
            - RewritePath=/kibana/(?<path>.*), /$\{path}
